// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AirportEventPayload } from "./AirportEventPayload";

export interface AirportEvent {
  from: string;
  payload: AirportEventPayload;
}
