// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Config {
  tick_duration: number;
  plane_spawn_chance: number;
  max_planes: number | null;
  cruising_altitude: number;
}
