// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Flight {
  airline: string;
  code: string;
  from: string;
  to: string;
  plane: string[];
}
