// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Waypoint } from "./Waypoint";

export interface FlightPlanner {
  instructions: null;
  route: Waypoint[];
  instruction_s: number;
  past_instructions: null;
  past_route: Waypoint[];
  past_pos: [number, number, number][];
}
