// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Target } from "./Target";

export interface Kinematics {
  x_target: Target[];
  y_target: Target[];
  v: [number, number];
}
