// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ModelMotion {
  max_v: [number, number];
  max_a: [number, number];
  turning_radius: number;
}
