// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Runway } from "./Runway";

export type PhaseData =
  | { Takeoff: { runway: Runway } }
  | "Cruise"
  | "Descent"
  | { Landing: { runway: Runway } };
