// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Flight } from "./Flight";
import type { PhaseData } from "./PhaseData";
import type { PlaneData } from "./PlaneData";
import type { PlaneEvent } from "./PlaneEvent";
import type { PlanePos } from "./PlanePos";

export interface Plane {
  id: string;
  pos: PlanePos;
  model: PlaneData;
  flight: Flight;
  phase: PhaseData;
  events: PlaneEvent[];
}
