// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelMotion } from "./ModelMotion";

export interface PlaneData {
  id: string;
  name: string;
  manufacturer: string;
  class: string;
  motion: ModelMotion;
  icon: string | null;
}
