// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Angle } from "./Angle";

export type Pos3Angle = [[number, number, number], Angle];
