// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Runway {
  name: string;
  start: [number, number];
  end: [number, number];
  altitude: number;
  class: string;
}
