on:
  workflow_dispatch:
  push:
    paths: ["**/Cargo.toml", "**/Cargo.lock"]
    
jobs:
  cargo-msrv:
    permissions:
      contents: write
      pull-requests: write
    uses: iiiii7d/cargo-msrv-workflow/.github/workflows/workflow.yml@263ddd37e4061f29cfccdd30992e3e58b680830c # main
